apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: eurowise
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.eurowise.svc.cluster.local:3306/eurowise
  SPRING_DATASOURCE_USERNAME: eurowise
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
