# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  acrName: eurowiseacr
  aksResourceGroup: expense-rg
  aksClusterName: eurowise-aks

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build and Push backend
      inputs:
        containerRegistry: acr-connection
        repository: eurowise-backend
        command: buildAndPush
        Dockerfile: '$(Build.SourcesDirectory)/Backend/Eurowise-rest-api-code/Dockerfile.multistage'
        buildContext: $(Build.SourcesDirectory)/Backend/Eurowise-rest-api-code
        tags: |
          $(Build.BuildId)
          latest
    
    - task: Docker@2
      displayName: Build and Push frontend
      inputs:
        containerRegistry: acr-connection
        repository: eurowise-frontend
        command: buildAndPush
        Dockerfile: Frontend/Expends/expenditure-app/Dockerfile
        buildContext: Frontend/Expends/expenditure-app
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    steps:
    - task: KubernetesManifest@1
      displayName: Deploy to AKS
      inputs:
        action: deploy
        connectionType: azureResourceManager
        azureSubscriptionConnection: azure-connection
        azureResourceGroup: $(aksResourceGroup)
        kubernetesCluster: $(aksClusterName)
        namespace: eurowise
        containers: |
          eurowiseacr.azurecr.io/eurowise-backend:$(Build.BuildId)
          eurowiseacr.azurecr.io/eurowise-frontend:$(Build.BuildId)
        manifests: |
          k8s/backend/deployment.yaml
          k8s/frontend/deployment.yaml    


