apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-keyvault
  namespace: monitoring
spec:
  provider: azure
  secretObjects: # 将从 Key Vault 中提取的秘密定义为 Kubernetes Secret 对象
    - secretName: grafana-secret
      type: Opaque
      data:
        - objectName: grafana-admin-user
          key: admin-user
        - objectName: grafana-admin-password
          key: admin-password
  parameters:
    usePodIdentity: "false" # 将此值设置为 "true" 以使用 Azure AD Pod Identity
    clientID: "3995473b-2990-44c6-923f-b9cdc7093dd5" # AKS managed identity 的客户端 ID, 之前echo出来的
    keyvaultName: eurowise-kv
    tenantID: "6f9e5876-9e32-4a11-9901-151c45c6fb4d" # Azure AD 租户 ID
    objects: |
      array:
        - |
          objectName: grafana-admin-user
          objectType: secret
        - |
          objectName: grafana-admin-password
          objectType: secret
