package com.hui.rest.webservices.restfulwebservices.user;


import com.hui.rest.webservices.restfulwebservices.expense.ExpenditureList;
import com.hui.rest.webservices.restfulwebservices.expense.repository.ExpenseRepository;
import com.hui.rest.webservices.restfulwebservices.expense.repository.UserRepository;
import com.hui.rest.webservices.restfulwebservices.security.JwtService;
import jakarta.annotation.Resource;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.List;
import java.util.Optional;



//Controller to handle HTTP related to user details
@RestController
public class UserJpaResource {

    //UserRepository dependency injection
    @Autowired
    private UserRepository repository;

    //ExpenseRepository dependency injection
    private ExpenseRepository expenseRepository;

    //PasswordEncoder dependency injection
    @Autowired
    private PasswordEncoder passwordEncoder;

    //AuthenticationManager dependency injection
    @Resource
    private AuthenticationManager authenticationManager;

    //JwtService dependency injection
    @Resource
    private JwtService jwtService;

    //Constructor
    public UserJpaResource(ExpenseRepository expenseRepository) {
        this.expenseRepository = expenseRepository;
    }

    //Process the GET method to retrieve all user details
    @GetMapping("/users")
    public List<User> retrieveAllUsers() {
        //Return all the users with status 0 from the user repository
        return repository.findAllByStatus(0);
    }

     //Process the POST method to register a new user
     @PostMapping("/register")
    public ResponseEntity<User> registerUser(@Valid @RequestBody User user) {
        //Declare a variable to store the value of given password
        String password = user.getPassword();

        //Set the password using the password encoder to enhance security
        user.setPassword(passwordEncoder.encode(password));

        //Handle the empty password case
        if (password == null || password.trim().isEmpty()) {
            System.out.println("Password cannot be null or empty");
        }

        //Declare a user variable to save the details of the user after encoding the password passed in
        User savedUser = repository.save(user);

        //Build a URL location for the frontend
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(savedUser.getId())
                .toUri();
        return ResponseEntity.created(location).build();
    }


    //Process the Post method to allow the user to login
    @PostMapping("/login")
    public ResponseEntity<User> login(@RequestBody User user) {

        //Pass the given username and password to authentication manager for authentication
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        user.getUsername(),
                        user.getPassword()
                )
        );

        //Retrieve the user details in the repository based on the given username
        user = repository.findByName(user.getUsername());

        //Declare a JWT token to store the token generated by the JWT service
        String jwtToken = jwtService.generateToken(user);

        //Set the generated token for the user
        user.setToken(jwtToken);

        //Return a response entity containing the user data and the HTTP request status in 200
        return new ResponseEntity(user, HttpStatusCode.valueOf(200));
    }


    //Process the Delete method to implement the deletion of a user
    @DeleteMapping("/users/{id}")
    public void deleteUser(@PathVariable long id) {
        repository.deleteById(id);
    }

    //Process the PUT method to modify the details of a user
    @PutMapping("/edit/users/{id}")
    public ResponseEntity<User> modifyUser(@PathVariable long id, @RequestBody User user) {

        try {
            //Retrieve the user with the provided id in the router
            Optional<User> optionalUser = repository.findById(id);

            //Use the condition logic to modify the user
            if (optionalUser.isPresent()) {
                //Retrieve the user details if it exists
                User existingUser = optionalUser.get();

                //Update the name if it is valid
                if (user.getName() != null) {
                    existingUser.setName(user.getName());
                }

                //Update the email if it is valid
                if (user.getEmail() != null) {
                    existingUser.setEmail(user.getEmail());
                }

                //Update the password if it is valid
                if (user.getPassword() != null) {
                    // Use the password encoder to encode the password
                    String encodedPassword = passwordEncoder.encode(user.getPassword());
                    existingUser.setPassword(encodedPassword);

                }

                //Update the role if it is valid
                if (user.getRole() != null) {
                    existingUser.setRole(user.getRole());
                }

                //Declare a user variable to store the modified user
                User modifiedUser = repository.save(existingUser);

                //Return a response entity with modified user object
                return ResponseEntity.ok(modifiedUser);
            } else {

                //Return a not found response entity
                return ResponseEntity.notFound().build();
            }
        } catch (Exception e) {
            //Handle the error case
            System.out.println("Error modifying user:");

            //Log the error details
            e.printStackTrace();

            //Return an internal server error response
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(null);
        }
    }


    //Process the POST method to add a new expense for the user
    @PostMapping("users/{id}/expenses")
    public ResponseEntity<Object> createExpenseForUser(@PathVariable long id,
                                                       @Valid @RequestBody ExpenditureList expense) {

        //Retrieve the user by provided id
        Optional<User> user = repository.findById(id);

        //Handle the user is empty case
        if (user.isEmpty()) {
            throw new UserNotFoundException("id:" + id);
        }

        //Set the user for the expense by retrieving the user details in repository
        expense.setUser(user.get());

        //Declare a variable to store the list of expense details by provided in request
        ExpenditureList savedExpense = expenseRepository.save(expense);

        //Build the URL location for the user
        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(savedExpense.getId())
                .toUri();
        return ResponseEntity.created(location).build();
    }

}

