apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: eurowise
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: eurowise
  MYSQL_USER: eurowise
  MYSQL_PASSWORD: eurowise123
