apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.global.namespace }}
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql.{{ .Values.global.namespace }}.svc.cluster.local:3306/expensedb
  SPRING_DATASOURCE_USERNAME: expenseuser 
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"